#include "ref_runtime.h"
#include <assert.h>
#include <stdio.h>

static EventSlot spec(uint8_t service, PeripheralId p, Criticality c, uint16_t tx) {
    EventSlot e={0}; e.type=EVT_PERIPHERAL_READ; e.producer_id=1u; e.service_id=service; e.consumer_id=service; e.peripheral=p; e.criticality=c; e.transaction_id=tx; e.degradable=c!=CRITICAL; e.shared_state_valid=true; return e;
}
static void admit4(Runtime*rt,EventRef*a,EventRef*b,EventRef*c,EventRef*d){EventSlot e1=spec(1u,PERIPH_I2C0,NORMAL,1u),e2=spec(2u,PERIPH_I2C0,NORMAL,2u),e3=spec(3u,PERIPH_I2C0,NORMAL,3u),e4=spec(4u,PERIPH_UART0,DEFERABLE,4u);assert(runtime_admit(rt,&e1,a)==OUTCOME_SUCCESS);assert(runtime_admit(rt,&e2,b)==OUTCOME_SUCCESS);assert(runtime_admit(rt,&e3,c)==OUTCOME_SUCCESS);assert(runtime_admit(rt,&e4,d)==OUTCOME_SUCCESS);}
static void test_W01_independent_preservation(void){Runtime rt;runtime_init(&rt,VAR_P4_INTEGRATED);EventRef e1,e2,e3,e4;admit4(&rt,&e1,&e2,&e3,&e4);assert(runtime_start_fault(&rt,FAULT_I2C_NACK,ASSOC_EXACT,e2,2u,NORMAL,true,true,true)==OUTCOME_SUCCESS);EventRef s;assert(scheduler_select(&rt,&s)&&event_ref_equal(s,e1));assert(runtime_execute_selected(&rt,s,NULL,NULL)==OUTCOME_SUCCESS);assert(scheduler_select(&rt,&s)&&event_ref_equal(s,e3));assert(runtime_execute_selected(&rt,s,NULL,NULL)==OUTCOME_SUCCESS);assert(scheduler_select(&rt,&s)&&event_ref_equal(s,e4));assert(runtime_execute_selected(&rt,s,NULL,NULL)==OUTCOME_SUCCESS);assert(runtime_apply_policy(&rt,NULL)==OUTCOME_SUCCESS);}
static void test_W02_ordered_blocking(void){Runtime rt;runtime_init(&rt,VAR_P4_INTEGRATED);EventRef e1,e2,e3;EventSlot s1=spec(1u,PERIPH_I2C0,NORMAL,1u),s2=spec(2u,PERIPH_I2C0,NORMAL,2u),s3=spec(3u,PERIPH_UART0,NORMAL,3u);assert(runtime_admit(&rt,&s1,&e1)==OUTCOME_SUCCESS);assert(runtime_admit(&rt,&s2,&e2)==OUTCOME_SUCCESS);assert(runtime_admit(&rt,&s3,&e3)==OUTCOME_SUCCESS);assert(runtime_add_dependency(&rt,e2,e1,DEP_ORDERED,ST_COMPLETED)==OUTCOME_SUCCESS);assert(runtime_start_fault(&rt,FAULT_I2C_NACK,ASSOC_EXACT,e1,1u,NORMAL,true,true,true)==OUTCOME_SUCCESS);EventRef s;assert(scheduler_select(&rt,&s)&&event_ref_equal(s,e3));assert(!event_ref_equal(s,e2));}
static void test_W03_coupled_containment(void){Runtime rt;runtime_init(&rt,VAR_P4_INTEGRATED);EventRef e1,e2;EventSlot a=spec(1u,PERIPH_I2C0,NORMAL,10u),b=spec(1u,PERIPH_I2C0,NORMAL,10u);assert(runtime_admit(&rt,&a,&e1)==OUTCOME_SUCCESS);assert(runtime_admit(&rt,&b,&e2)==OUTCOME_SUCCESS);assert(runtime_add_dependency(&rt,e2,e1,DEP_COUPLED,ST_COMPLETED)==OUTCOME_SUCCESS);assert(runtime_start_fault(&rt,FAULT_I2C_NACK,ASSOC_EXACT,e1,10u,NORMAL,true,true,true)==OUTCOME_SUCCESS);EventRef s;assert(!scheduler_select(&rt,&s));}
static void test_W04_shared_peripheral_noncausality(void){Runtime rt;runtime_init(&rt,VAR_P4_INTEGRATED);EventRef e1,e2,e3;EventSlot a=spec(1u,PERIPH_I2C0,NORMAL,11u),b=spec(2u,PERIPH_I2C0,NORMAL,12u),c=spec(3u,PERIPH_I2C0,NORMAL,13u);assert(runtime_admit(&rt,&a,&e1)==OUTCOME_SUCCESS);assert(runtime_admit(&rt,&b,&e2)==OUTCOME_SUCCESS);assert(runtime_admit(&rt,&c,&e3)==OUTCOME_SUCCESS);assert(runtime_start_fault(&rt,FAULT_I2C_NACK,ASSOC_EXACT,e1,11u,NORMAL,true,true,true)==OUTCOME_SUCCESS);EventRef s;assert(scheduler_select(&rt,&s)&&event_ref_equal(s,e2));}
static void test_W05_retry_success(void){Runtime rt;runtime_init(&rt,VAR_P4_INTEGRATED);EventRef e;EventSlot a=spec(1u,PERIPH_I2C0,NORMAL,20u);assert(runtime_admit(&rt,&a,&e)==OUTCOME_SUCCESS);FaultInjection f={FAULT_I2C_NACK,e,20u,99u,0u,true};assert(runtime_start_fault(&rt,FAULT_I2C_NACK,ASSOC_EXACT,e,20u,NORMAL,true,true,true)==OUTCOME_SUCCESS);assert(runtime_apply_policy(&rt,&f)==OUTCOME_SUCCESS);assert(!rt.episode_in_use);}
static void test_W06_retry_retry_reinit(void){Runtime rt;runtime_init(&rt,VAR_P4_INTEGRATED);EventRef e;EventSlot a=spec(1u,PERIPH_I2C0,NORMAL,21u);assert(runtime_admit(&rt,&a,&e)==OUTCOME_SUCCESS);FaultInjection f={FAULT_I2C_TIMEOUT,e,21u,1u,0u,true};assert(runtime_start_fault(&rt,FAULT_I2C_TIMEOUT,ASSOC_EXACT,e,21u,NORMAL,true,true,true)==OUTCOME_SUCCESS);assert(runtime_apply_policy(&rt,&f)==OUTCOME_FAILURE);f.trigger_action_index=2u;assert(runtime_apply_policy(&rt,&f)==OUTCOME_FAILURE);f.trigger_action_index=99u;assert(runtime_apply_policy(&rt,&f)==OUTCOME_SUCCESS);assert(!rt.episode_in_use);}
static void test_W07_degrade(void){Runtime rt;runtime_init(&rt,VAR_P4_INTEGRATED);EventRef e;EventSlot a=spec(1u,PERIPH_I2C0,DEFERABLE,22u);assert(runtime_admit(&rt,&a,&e)==OUTCOME_SUCCESS);FaultInjection f={FAULT_I2C_PERSISTENT,e,22u,1u,0u,true};assert(runtime_start_fault(&rt,FAULT_I2C_PERSISTENT,ASSOC_EXACT,e,22u,DEFERABLE,false,false,true)==OUTCOME_SUCCESS);assert(runtime_apply_policy(&rt,&f)==OUTCOME_TERMINAL_DEGRADE);}
static void test_W08_escalate(void){Runtime rt;runtime_init(&rt,VAR_P4_INTEGRATED);EventRef e;EventSlot a=spec(1u,PERIPH_I2C0,CRITICAL,23u);assert(runtime_admit(&rt,&a,&e)==OUTCOME_SUCCESS);assert(runtime_start_fault(&rt,FAULT_I2C_PERSISTENT,ASSOC_UNKNOWN,e,23u,CRITICAL,false,false,false)==OUTCOME_SUCCESS);assert(runtime_apply_policy(&rt,NULL)==OUTCOME_TERMINAL_ESCALATE);}
static void test_W09_queue_boundary(void){Runtime rt;runtime_init(&rt,VAR_P4_INTEGRATED);EventSlot a=spec(1u,PERIPH_I2C0,NORMAL,30u);EventRef r;for(unsigned i=0;i<QMAX;i++)assert(runtime_admit(&rt,&a,&r)==OUTCOME_SUCCESS);assert(runtime_admit(&rt,&a,&r)==OUTCOME_QUEUE_FULL);}
static void test_W10_quarantine_boundary(void){Runtime rt;runtime_init(&rt,VAR_P4_INTEGRATED);EventRef r[XMAX];EventSlot a=spec(1u,PERIPH_I2C0,NORMAL,40u);for(unsigned i=0;i<XMAX;i++)assert(runtime_admit(&rt,&a,&r[i])==OUTCOME_SUCCESS);assert(runtime_start_fault(&rt,FAULT_I2C_NACK,ASSOC_EXACT,r[0],40u,NORMAL,true,true,true)==OUTCOME_SUCCESS);assert(runtime_start_fault(&rt,FAULT_I2C_NACK,ASSOC_EXACT,r[1],40u,NORMAL,true,true,true)==OUTCOME_EPISODE_FULL);}
static void test_W11_stale_generation(void){Runtime rt;runtime_init(&rt,VAR_P4_INTEGRATED);EventSlot a=spec(1u,PERIPH_I2C0,NORMAL,50u);EventRef old,new,refs[QMAX];assert(runtime_admit(&rt,&a,&old)==OUTCOME_SUCCESS);for(unsigned i=1u;i<QMAX;i++)assert(runtime_admit(&rt,&a,&refs[i])==OUTCOME_SUCCESS);rt.slots[old.slot_id].state=ST_COMPLETED;for(unsigned i=0u;i+1u<rt.queue_count;i++)rt.queue[i]=rt.queue[i+1u];--rt.queue_count;assert(runtime_admit(&rt,&a,&new)==OUTCOME_SUCCESS);assert(new.slot_id==old.slot_id);assert(old.generation!=new.generation);assert(!event_ref_valid(&rt,old));assert(event_ref_valid(&rt,new));}
static void test_W12_association_ambiguity(void){Runtime rt;runtime_init(&rt,VAR_P4_INTEGRATED);EventRef e;EventSlot a=spec(1u,PERIPH_I2C0,NORMAL,60u);assert(runtime_admit(&rt,&a,&e)==OUTCOME_SUCCESS);assert(runtime_start_fault(&rt,FAULT_AMBIGUOUS,ASSOC_PERIPHERAL_ONLY,event_ref_invalid(),INVALID_TX,NORMAL,true,true,true)==OUTCOME_SUCCESS);assert(!rt.slots[e.slot_id].fault_associated);OutcomeCode out=runtime_apply_policy(&rt,NULL);assert(out==OUTCOME_TERMINAL_DEGRADE||out==OUTCOME_TERMINAL_ESCALATE);assert(!rt.episode_in_use);}
static void test_W13_criticality_degradability(void){Runtime rt;runtime_init(&rt,VAR_P4_INTEGRATED);EventRef e;EventSlot a=spec(1u,PERIPH_I2C0,CRITICAL,70u);assert(runtime_admit(&rt,&a,&e)==OUTCOME_SUCCESS);assert(runtime_start_fault(&rt,FAULT_I2C_PERSISTENT,ASSOC_EXACT,e,70u,CRITICAL,false,false,false)==OUTCOME_SUCCESS);assert(runtime_apply_policy(&rt,NULL)==OUTCOME_TERMINAL_ESCALATE);}
static void test_W14_mixed_and_capacity_constants(void){Runtime rt;runtime_init(&rt,VAR_P4_INTEGRATED);EventRef e[4];admit4(&rt,&e[0],&e[1],&e[2],&e[3]);assert(runtime_add_dependency(&rt,e[1],e[0],DEP_ORDERED,ST_COMPLETED)==OUTCOME_SUCCESS);assert(runtime_add_dependency(&rt,e[2],e[1],DEP_COUPLED,ST_COMPLETED)==OUTCOME_SUCCESS);assert(DMAX==4u&&QMAX==16u&&XMAX==4u&&EPMAX==1u);}
static void test_recovery_bound(void){Runtime rt;runtime_init(&rt,VAR_P4_INTEGRATED);EventRef e;EventSlot a=spec(1u,PERIPH_I2C0,NORMAL,80u);assert(runtime_admit(&rt,&a,&e)==OUTCOME_SUCCESS);FaultInjection f={FAULT_I2C_PERSISTENT,e,80u,1u,0u,true};assert(runtime_start_fault(&rt,FAULT_I2C_PERSISTENT,ASSOC_EXACT,e,80u,NORMAL,true,true,true)==OUTCOME_SUCCESS);assert(runtime_apply_policy(&rt,&f)==OUTCOME_FAILURE);f.trigger_action_index=2u;assert(runtime_apply_policy(&rt,&f)==OUTCOME_FAILURE);f.trigger_action_index=3u;assert(runtime_apply_policy(&rt,&f)==OUTCOME_FAILURE);assert(runtime_apply_policy(&rt,&f)==OUTCOME_TERMINAL_DEGRADE);assert(rt.episode.attempt_count==3u);}
static void test_trace_metadata(void){Runtime rt;runtime_init(&rt,VAR_P4_INTEGRATED);runtime_set_trace_metadata(&rt,1234u,14u,7u);EventRef e;EventSlot a=spec(1u,PERIPH_I2C0,NORMAL,90u);assert(runtime_admit(&rt,&a,&e)==OUTCOME_SUCCESS);assert(rt.trace_count>0u);assert(rt.trace[0].run_id==1234u);assert(rt.trace[0].event_ref.slot_id==e.slot_id);assert(rt.trace[0].event_ref.generation==e.generation);}
static void test_policy_properties(void){Runtime rt;runtime_init(&rt,VAR_P4_INTEGRATED);for(unsigned f=0;f<=FAULT_AMBIGUOUS;f++)for(unsigned a=0;a<=ASSOC_UNKNOWN;a++)for(unsigned n=0;n<4;n++)for(unsigned c=0;c<3;c++){FaultContext ctx={0};ctx.fault_class=(FaultClass)f;ctx.association=(AssociationLevel)a;ctx.attempt_count=(uint8_t)n;ctx.criticality=(Criticality)c;ctx.retry_safe=true;ctx.reinit_safe=true;ctx.degrade_safe=true;ctx.dependencies_safe=true;ctx.shared_state_valid=true;ctx.episode_state=EP_ACTIVE;ctx.active=true;PolicyDecision d=policy_decide(&rt,&ctx);assert(d.action<=ACT_ESCALATE);assert(d.target_scope>=ctx.association);assert(d.attempt_index<=3u);if(d.terminal)assert(d.action==ACT_DEGRADE||d.action==ACT_ESCALATE);}}
static void test_static_accounting(void){assert(runtime_static_bytes()==sizeof(Runtime));assert(runtime_slot_bytes()==sizeof(EventSlot));assert(runtime_trace_bytes()==sizeof(TraceRecord)*TRACE_EVENT_CAP);}
int main(void){test_W01_independent_preservation();test_W02_ordered_blocking();test_W03_coupled_containment();test_W04_shared_peripheral_noncausality();test_W05_retry_success();test_W06_retry_retry_reinit();test_W07_degrade();test_W08_escalate();test_W09_queue_boundary();test_W10_quarantine_boundary();test_W11_stale_generation();test_W12_association_ambiguity();test_W13_criticality_degradability();test_W14_mixed_and_capacity_constants();test_recovery_bound();test_trace_metadata();test_policy_properties();test_static_accounting();puts("PASS: W01-W14 + recovery bound + policy properties + static accounting");return 0;}
